### ISSUE TITLE
bug in example sweep application

### ISSUE THREAD

**Issue by rossgrady** [CedarGroveStudios/CircuitPython_AD9833#2]
https://github.com/CedarGroveStudios/CircuitPython_AD9833/blob/0110af9cdf71ad61581899f50d188ab4e8b2f397/examples/AD9833_ADSR_FeatherWing_sweep_v03.py#L60

The setter for wave type is lowercase -- I had to change this to `wave_gen.wave_type = WAVE_TYPE` & now it works for me.

Thanks for this, by the way -- it's exactly what I needed for a project I'm working on!

**Comment by CedarGroveStudios** [comment]
Thank you!
